/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tw.cn.cap.gtb.todo;

import com.tw.cn.cap.gtb.todo.command.Command;
import com.tw.cn.cap.gtb.todo.util.CommonUtils;

import java.util.List;

public class App {
    public static void main(String[] args) {
        run(args);
    }
    public static void run(String... args) {
        Command command = CommonUtils.getCommand(args);
        command.execute(args);
    }
}
